# Generated by Django 4.2.28 on 2026-02-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('currency', 'نرخ ارز'), ('gold', 'نرخ طلا و نقره'), ('crypto', 'بازار کریپتو')], default='currency', max_length=10),
        ),
    ]
