# Generated by Django 4.2.28 on 2026-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricess', '0002_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('currency', 'نرخ ارز'), ('gold', 'نرخ طلا و نقره'), ('crypto', 'بازار کریپتو'), ('oil', 'نرخ نفت')], default='currency', max_length=10),
        ),
    ]
